---
- name: Make sure satellite is accessible from host
  lineinfile:
    path: /etc/hosts
    line: "{{ satellite_ip }}  {{ satellite_fqdn }}"

- name: Clean subscription manager data
  shell: |
    rm -rf /etc/pki/product/product
    cp /etc/pki/product-default/328.pem /etc/pki/product/
    rm -rf /etc/pki/consumer
    rm -rf /etc/pki/entitlement
    subscription-manager clean

- name: Install catello rpm
  yum:
    name: "http://{{ satellite_fqdn }}/pub/katello-ca-consumer-latest.noarch.rpm"
    state: present

- name: Attach satellite subscription
  redhat_subscription:
    state: present
    activationkey: "{{ satellite_key }}"
    org_id: "{{ satellite_org }}"
    auto_attach: yes