---

####  Main role logic

- name: Prepare facts
  set_fact:
    ws_fqdn: "{{ ansible_facts.os_family|default('win')|lower ~ '-ws' ~ (play_hosts.index(inventory_hostname) + 1) }}"

#### Importing tasks for setting up windows servers during Demo

- name:  View hosts winsvc role is about to be applied on
  import_tasks: view_hosts.yml
  when: view_hosts|bool == True

- name:  Importing tasks for basic preparation of windows hosts
  import_tasks: server_prep_basic.yml
  when: var_prep_basic|bool == True

- name:  Importing DC domain member tasks
  import_tasks: server_ad_add.yml
  when: var_ad_add|bool == True

- name:  Importing tasks for setting up firewall rules
  import_tasks: server_firewall_add.yml
  when: var_firewall_add|bool == True

- name:  Importing taks for setting up software with using chocolatey
  import_tasks: server_chocolatey_add.yml
  when: var_chocolatey_add|bool == True

- name:  Importing taks for setting up software with using standard functions
  import_tasks: server_msi_add.yml
  when: var_msi_add|bool == True
