- name: Adding hosts to the domain
  win_domain_membership:
    dns_domain_name: "{{domain_dns_name}}"
    hostname: "{{ ws_fqdn }}"
#    hostname: "{{ lookup('password', '/dev/null chars=ascii_lowercase length=6') }}"
    domain_admin_user: "{{domain_ad_user}}@{{ domain_dns_name }}"
    domain_admin_password: "{{domain_ad_password}}"
    state: domain

- name: Reboot servers to apply changes
  win_reboot:
  when: var_prep_ad_reboot|bool == True