- name: Change the hostname to the ansible inventory hostname
  win_hostname:
    name: "{{inventory_hostname}}"

- name: Setting up DNS client to work with our local DC
  win_dns_client:
    adapter_names: "{{basic_adapter_name}}"
    ipv4_addresses: "{{basic_dns_address}"