- name: Configure the hostname
  win_hostname:
    name: "{{ ws_fqdn }}"
  when: var_prep_hosname_rn|bool == True

- name: Setting up DNS client to work with our local DC
  win_dns_client:
    adapter_names: "{{basic_adapter_name}}"
    ipv4_addresses: "{{ basic_dns_address }}"

- name: Reboot servers to apply changes
  win_reboot:
  when: var_prep_hosname_reboot|bool == True